name: 'Install Python and Dependencies'
description: 'Installs Python and project dependencies'
inputs:
  python-version:
    description: 'Version of Python to install'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Dependencies with Retry
      shell: bash
      run: |
        max_attempts=5
        sleep_seconds=10
        attempt_num=1
        until pip install .; do
          echo "Attempt $attempt_num of $max_attempts failed! Trying again in $sleep_seconds seconds..."
          sleep $sleep_seconds
          ((attempt_num++))
          if [[ $attempt_num -eq $max_attempts ]]; then
            echo "All $max_attempts attempts have failed!"
            exit 1
          fi
        done
