#
# pip install .

name: install_self

on:
  workflow_call:

jobs:
  install_self:
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-
    - name: Install Dependencies with Retry
      run: |
        cp packaging/setup.py .
        max_attempts=5
        sleep_seconds=10
        attempt_num=1
        until timeout $sleep_seconds pip install . || [[ $attempt_num -eq $max_attempts ]]
        do
          echo "Attempt $attempt_num of $max_attempts failed! Trying again in $sleep_seconds seconds..."
          sleep $sleep_seconds
          ((attempt_num++))
        done

        if [[ $attempt_num -eq $max_attempts ]]; then
          echo "All $max_attempts attempts have failed!"
          exit 1
        fi
