# INJECT THE C EXTENSION INTO THE AUTOGENERATED setup.py, RUN BEFORE BUILDING WHEELS:
#   cp packaging/setup.py setup.py && python packaging/add_speedups.py setup.py
# --required MAKES A COMPILE FAILURE FAIL THE BUILD (WHEEL BUILDS); DEFAULT IS optional
import sys

path = sys.argv[1]
optional = "" if "--required" in sys.argv else ", optional=True"
with open(path) as f:
    text = f.read()
if "_speedups" in text:
    sys.exit(0)
text = text.replace("from setuptools import setup", "from setuptools import setup, Extension", 1)
text = text.replace(
    "setup(",
    f"setup(\n    ext_modules=[Extension('mo_dots._speedups', sources=['mo_dots/_speedups.c']{optional})],",
    1,
)
with open(path, "w") as f:
    f.write(text)
