# INJECT THE OPTIONAL C EXTENSION INTO THE AUTOGENERATED setup.py:
#   cp packaging/setup.py setup.py && python packaging/add_speedups.py setup.py
# A COMPILE FAILURE FALLS BACK TO PURE PYTHON; EVERY BINARY-WHEEL TEST ASSERTS
# THE ACCELERATOR IS ACTIVE, WHICH IS WHAT MAKES IT REQUIRED THERE
import sys

path = sys.argv[1]
with open(path) as f:
    text = f.read()
if "_speedups" in text:
    sys.exit(0)
text = text.replace("from setuptools import setup", "from setuptools import setup, Extension", 1)
text = text.replace(
    "setup(",
    "setup(\n    ext_modules=[Extension('mo_dots._speedups', sources=['mo_dots/_speedups.c'], optional=True)],",
    1,
)
with open(path, "w") as f:
    f.write(text)
