# SYNCED FROM mo-deploy BY EVERY DEPLOY; EDIT THERE
# encoding: utf-8
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.
#
# Author: Kyle Lahnakoski (kyle@lahnakoski.com)
#
"""Render packaging/setuptools.json into a repo-root setup.py:

    python -m mo_deploy.gen_setup [DIR]

stdlib only, so the copy synced to each repo's packaging/ runs anywhere
without installing anything.
"""
import json
import sys
from pathlib import Path

SETUPTOOLS = "packaging/setuptools.json"  # CONFIGURATION USED TO MAKE THE setup.py FILE


def gen_setup_py_file(clone_dir):
    print("write setup.py")
    clone_dir = Path(clone_dir)
    setup = apply_functions(json.loads((clone_dir / SETUPTOOLS).read_text(encoding="utf-8-sig")))
    if setup.get("ext_modules"):
        imports = "import os\nfrom setuptools import setup, Extension\n"
    else:
        imports = "from setuptools import setup\n"
    content = (
        "# encoding: utf-8\n"
        + "# THIS FILE IS AUTOGENERATED!\n"
        + imports
        + "setup(\n"
        + ",\n".join(
            "    " + k + "=" + setup_py_value(setup["name"], k, v) for k, v in setup.items() if v is not None
        )
        + "\n"
        + ")"
    )
    (clone_dir / "setup.py").write_text(content, encoding="utf8")
    # FOR SOME REASON tests GET INCLUDED
    (clone_dir / "MANIFEST.in").write_text("global-exclude tests/*\nglobal-exclude MANIFEST.in\n", encoding="utf8")


def apply_functions(node):
    # SAME EXPANSION mo_files.read_json APPLIES: {"$concat": [...], "separator": s}
    if isinstance(node, dict):
        if "$concat" in node:
            return (node.get("separator") or "").join(apply_functions(v) for v in node["$concat"])
        return {k: apply_functions(v) for k, v in node.items() if v is not None}
    if isinstance(node, list):
        return [apply_functions(v) for v in node]
    return node


def setup_py_value(package_name, key, value):
    if key != "ext_modules":
        return value2python(value)
    # ext_modules IS A LIST OF Extension KWARGS; PURE (py3-none-any) BUILDS
    # SET <NAME>_NO_EXTENSIONS TO DROP THEM
    no_ext = package_name.upper().replace("-", "_") + "_NO_EXTENSIONS"
    extensions = ", ".join(
        "Extension(" + ", ".join(k + "=" + value2python(v) for k, v in e.items()) + ")" for e in value
    )
    return '[] if os.environ.get("' + no_ext + '") else [' + extensions + "]"


def value2python(value):
    if isinstance(value, list):
        return "[" + ", ".join(value2python(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(value2python(k) + ": " + value2python(v) for k, v in value.items()) + "}"
    return repr(value)


if __name__ == "__main__":
    gen_setup_py_file(sys.argv[1] if len(sys.argv) > 1 else ".")
