# SYNCED FROM mo-deploy BY EVERY DEPLOY; EDIT THERE
# encoding: utf-8
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.
#
# Author: Kyle Lahnakoski (kyle@lahnakoski.com)
#
"""Render packaging/setuptools.json into a repo-root setup.py:

    python -m mo_deploy.gen_setup [DIR]
"""
import sys

from mo_dots import exists
from mo_files import File
from mo_future import is_binary, is_text, text
from mo_json import value2json
from mo_logs import logger

SETUPTOOLS = "packaging/setuptools.json"  # CONFIGURATION USED TO MAKE THE setup.py FILE


def gen_setup_py_file(clone_dir):
    logger.info("write setup.py")
    setup = File(clone_dir / SETUPTOOLS).read_json(flexible=False)
    if exists(setup.ext_modules):
        imports = "import os\nfrom setuptools import setup, Extension\n"
    else:
        imports = "from setuptools import setup\n"
    content = (
        "# encoding: utf-8\n"
        + "# THIS FILE IS AUTOGENERATED!\n"
        + imports
        + "setup(\n"
        + ",\n".join(
            "    " + k + "=" + setup_py_value(setup.name, k, v) for k, v in setup.items() if exists(v)
        )
        + "\n"
        + ")"
    )
    (clone_dir / "setup.py").write(content)
    # FOR SOME REASON tests GET INCLUDED
    (clone_dir / "MANIFEST.in").write("global-exclude tests/*\nglobal-exclude MANIFEST.in\n")


def setup_py_value(package_name, key, value):
    if key != "ext_modules":
        return value2python(value)
    # ext_modules IS A LIST OF Extension KWARGS; PURE (py3-none-any) BUILDS
    # SET <NAME>_NO_EXTENSIONS TO DROP THEM
    no_ext = package_name.upper().replace("-", "_") + "_NO_EXTENSIONS"
    extensions = ", ".join(
        "Extension(" + ", ".join(k + "=" + value2python(v) for k, v in e.items()) + ")" for e in value
    )
    return '[] if os.environ.get("' + no_ext + '") else [' + extensions + "]"


def value2python(value):
    if value in (True, False, None):
        return text(repr(value))
    elif is_text(value):
        return text(repr(value))
    elif is_binary(value):
        return text(repr(value))
    else:
        return value2json(value)


if __name__ == "__main__":
    gen_setup_py_file(File(sys.argv[1] if len(sys.argv) > 1 else "."))
