name: Install Dependencies
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.python-version }}-
          ${{ runner.os }}-pip-
    - name: Install Dependencies with Retry
      run: |
        max_attempts=5
        sleep_seconds=10
        attempt_num=1
        until timeout $sleep_seconds pip install . || [[ $attempt_num -eq $max_attempts ]]
        do
          echo "Attempt $attempt_num of $max_attempts failed! Trying again in $sleep_seconds seconds..."
          sleep $sleep_seconds
          ((attempt_num++))
        done

        if [[ $attempt_num -eq $max_attempts ]]; then
          echo "All $max_attempts attempts have failed!"
          exit 1
        fi
